language: node_js

node_js:
  - "12.14"

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.npm"


before_deploy:
  - zip -r groupTalkServer *
  - mkdir -p deploy
  - mv groupTalkServer.zip deploy/groupTalkServer.zip

deploy:
    provider: s3 # AWS S3를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: development-blog-image # S3에 생성한 버킷
    region: ap-northeast-2
    skip_cleanup: true 
    acl: public_read
    local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
    wait-until-deployed: true
    on:
      repo: gunwook/groupTalkRelase #Github 주소
      branch: master

notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - eorjstldzm@gmail.com
