language: node_js

node_js:
  - "10.13"

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.npm"


before_deploy:
  - rm -rf node_modules
  - zip -r groupTalkServer *
  - mkdir -p deploy
  - mv groupTalkServer.zip deploy/groupTalkServer.zip

deploy:
    provider: s3 # AWS S3를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: development-blog-image # S3에 생성한 버킷
    region: ap-northeast-2
    skip_cleanup: true 
    acl: public_read
    local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
    wait-until-deployed: true
    on:
      repo: gunwook/groupTalkRelase #Github 주소
      branch: master
      
    provider: codedeploy # AWS CodeDeploy를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY   # Travis repo settings에 설정된 값
    bucket: development-blog-image # AWS CodeDeploy가 다운로드 받은 버킷
    key: node-group-server.zip # 해당 버킷에 저장되어 있는 파일 이름
    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
    application: group-talk-service # AWS 배포 애플리케이션
    deployment_group: group-talk-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: gunwook/groupTalkRelase
      branch: master


notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - eorjstldzm@gmail.com


      