language: node_js

node_js:
  - "12.14"

branches:
  only:
    - master

notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - eorjstldzm@gmail.com

before_deploy:
  - rm -rf node_modules
  - zip -r --exclude=\*.git\* --exclude=\*.node_modules\* --exclude=\*.log\* groupTalkServer.zip *
  - mkdir -p deploy
  - mv node-group-server.zip deploy/node-group-server.zip
